package com.tbtechs.focusflow.ui.profile

import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.weight
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.Key
import androidx.compose.material.icons.outlined.Refresh
import androidx.compose.material3.AlertDialog
import androidx.compose.material3.Button
import androidx.compose.material3.CircularProgressIndicator
import androidx.compose.material3.FilterChip
import androidx.compose.material3.Icon
import androidx.compose.material3.IconButton
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.OutlinedTextField
import androidx.compose.material3.Text
import androidx.compose.material3.TextButton
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.rememberCoroutineScope
import androidx.compose.runtime.setValue
import androidx.compose.ui.Modifier
import androidx.compose.ui.text.input.PasswordVisualTransformation
import androidx.compose.ui.text.input.VisualTransformation
import androidx.compose.ui.unit.dp
import kotlinx.coroutines.launch
import java.security.SecureRandom

enum class PinType { FOCUS, DEFENSE }

@Composable
fun PinSetupModal(
    visible: Boolean,
    pinType: PinType,
    onSaved: (String) -> Boolean,
    onCancel: () -> Unit,
) {
    if (!visible) return
    val scope = rememberCoroutineScope()
    var generated by remember(visible) { mutableStateOf(randomPassword()) }
    var custom by remember(visible) { mutableStateOf(true) }
    var password by remember(visible) { mutableStateOf("") }
    var confirmation by remember(visible) { mutableStateOf("") }
    var acknowledged by remember(visible) { mutableStateOf(false) }
    var showPassword by remember { mutableStateOf(false) }
    var showConfirmation by remember { mutableStateOf(false) }
    var saving by remember { mutableStateOf(false) }
    var error by remember { mutableStateOf<String?>(null) }

    fun save(raw: String) {
        if (raw.length < 8) {
            error = "Password must be at least 8 characters."
            return
        }
        if (COMMON_PASSWORDS.contains(raw.lowercase())) {
            error = "This password is too common — choose something unique."
            return
        }
        scope.launch {
            saving = true
            error = null
            val saved = runCatching { onSaved(raw) }.getOrDefault(false)
            saving = false
            if (saved) onCancel() else error = "Could not save the password. Please try again."
        }
    }

    AlertDialog(
        onDismissRequest = onCancel,
        icon = { Icon(Icons.Outlined.Key, contentDescription = null) },
        title = { Text("Set ${pinType.label} Password") },
        text = {
            Column(verticalArrangement = Arrangement.spacedBy(10.dp)) {
                Text(pinType.description, style = MaterialTheme.typography.bodySmall)
                Row(horizontalArrangement = Arrangement.spacedBy(8.dp)) {
                    FilterChip(selected = custom, onClick = { custom = true; error = null }, label = { Text("I'll choose") })
                    FilterChip(selected = !custom, onClick = { custom = false; error = null }, label = { Text("Generate for me") })
                }
                if (custom) {
                    PasswordField(
                        value = password,
                        label = "Password (8+ characters)",
                        visible = showPassword,
                        onValueChange = { password = it; error = null },
                        onToggleVisibility = { showPassword = !showPassword },
                    )
                    PasswordField(
                        value = confirmation,
                        label = "Confirm password",
                        visible = showConfirmation,
                        onValueChange = { confirmation = it; error = null },
                        onToggleVisibility = { showConfirmation = !showConfirmation },
                    )
                    if (confirmation.isNotEmpty() && password != confirmation) {
                        Text("Passwords do not match", color = MaterialTheme.colorScheme.error)
                    }
                    Text(
                        passwordStrength(password),
                        style = MaterialTheme.typography.labelSmall,
                        color = if (password.length >= 8) MaterialTheme.colorScheme.primary else MaterialTheme.colorScheme.error,
                    )
                } else {
                    Row(verticalAlignment = androidx.compose.ui.Alignment.CenterVertically) {
                        Text(generated, modifier = Modifier.weight(1f), style = MaterialTheme.typography.titleMedium)
                        IconButton(onClick = { generated = randomPassword(); acknowledged = false; error = null }) {
                            Icon(Icons.Outlined.Refresh, contentDescription = "Generate another password")
                        }
                    }
                    Text("Write this down now. Only the hash is stored; there is no recovery option.", style = MaterialTheme.typography.bodySmall)
                        CheckboxRow(
                        checked = acknowledged,
                        onCheckedChange = { acknowledged = it; error = null },
                        label = "I have saved this password somewhere safe",
                    )
                }
                error?.let { Text(it, color = MaterialTheme.colorScheme.error) }
            }
        },
        confirmButton = {
            Button(
                enabled = !saving,
                onClick = {
                    if (custom) {
                        if (password != confirmation) error = "Passwords do not match."
                        else save(password)
                    } else if (!acknowledged) {
                        error = "Confirm you have saved this password before continuing."
                    } else {
                        save(generated)
                    }
                },
            ) {
                if (saving) CircularProgressIndicator()
                else Text(if (custom) "Set Password" else "Save Generated Password")
            }
        },
        dismissButton = { TextButton(onClick = onCancel) { Text("Cancel") } },
    )
}

@Composable
private fun PasswordField(
    value: String,
    label: String,
    visible: Boolean,
    onValueChange: (String) -> Unit,
    onToggleVisibility: () -> Unit,
) {
    Row(verticalAlignment = androidx.compose.ui.Alignment.CenterVertically) {
        OutlinedTextField(
            value = value,
            onValueChange = onValueChange,
            modifier = Modifier.weight(1f),
            label = { Text(label) },
            singleLine = true,
            visualTransformation = if (visible) VisualTransformation.None else PasswordVisualTransformation(),
        )
        TextButton(onClick = onToggleVisibility) { Text(if (visible) "Hide" else "Show") }
    }
}

private val COMMON_PASSWORDS = setOf(
    "password", "password1", "password123", "qwerty123", "qwerty",
    "abc123def", "iloveyou1", "admin1234", "letmein1", "welcome1",
    "12345678", "123456789", "1234567890", "11111111", "00000000",
    "aaaaaaaa", "bbbbbbbb", "zxcvbnm1", "focusflow", "focusflow1",
)

private fun passwordStrength(value: String): String {
    if (value.isEmpty()) return "Use at least 8 characters."
    if (value.length < 8) return "${value.length}/8 characters minimum"
    val variety = listOf(
        value.any { it.isUpperCase() },
        value.any { it.isLowerCase() },
        value.any { it.isDigit() },
        value.any { !it.isLetterOrDigit() },
    ).count { it }
    return when {
        value.length >= 16 && variety >= 3 -> "Very strong"
        value.length >= 12 && variety >= 2 -> "Strong"
        variety >= 2 -> "Fair — try adding symbols or numbers"
        else -> "Weak — mix uppercase, lowercase, numbers and symbols"
    }
}

private fun randomPassword(length: Int = 16): String {
    val chars = "ABCDEFGHJKLMNPQRSTUVWXYZabcdefghjkmnpqrstuvwxyz23456789@#!$"
    val random = SecureRandom()
    return buildString(length) { repeat(length) { append(chars[random.nextInt(chars.length)]) } }
}

private val PinType.label: String
    get() = if (this == PinType.FOCUS) "Focus Session" else "Defense"

private val PinType.description: String
    get() = if (this == PinType.FOCUS) {
        "Required to end an active focus session."
    } else {
        "Required before disabling protection or removing restrictions."
    }

@Composable
private fun CheckboxRow(
    checked: Boolean,
    onCheckedChange: (Boolean) -> Unit,
    label: String,
) {
    Row(
        modifier = Modifier.fillMaxWidth().padding(vertical = 4.dp),
        verticalAlignment = androidx.compose.ui.Alignment.CenterVertically,
    ) {
        androidx.compose.material3.Checkbox(checked = checked, onCheckedChange = onCheckedChange)
        Text(label, style = MaterialTheme.typography.bodySmall)
    }
}